/* =========================================================
   LAVENZA — Product Database
   =========================================================
   Every product MUST have:
   - id, name, brand, category, subCategory
   - description, price, mrp, unit, discount
   - rating, reviewCount, stockStatus
   - images (array)
   - attributes (object — dynamic specs)
   - tags (array)
   - featured (bool), newArrival (bool)
   ========================================================= */

const dummyProducts = [
  /* ============ SKINCARE ============ */
  {
    id: "P001",
    name: "Glow Vitamin C Serum",
    brand: "Lavenza",
    category: "Skincare",
    subCategory: "Face Serum",
    description: "Lightweight vitamin C serum for a brighter and healthier-looking complexion.",
    price: 399, mrp: 499, unit: "30 ml", discount: 20,
    rating: 4.7, reviewCount: 128, stockStatus: "In Stock",
    images: ["images/vitamin-c-1.jpg", "images/vitamin-c-2.jpg", "images/vitamin-c-3.jpg"],
    attributes: { "Skin Type": "All Skin Types", "Key Ingredient": "Vitamin C", "Volume": "30 ml", "Country": "India" },
    tags: ["Vitamin C", "Serum", "Skincare", "Face"],
    featured: true, newArrival: false
  },
  {
    id: "P002",
    name: "Hydra Glow Moisturizer",
    brand: "Lavenza",
    category: "Skincare",
    subCategory: "Moisturizer",
    description: "24-hour hydration moisturizer with hyaluronic acid for soft, plump skin.",
    price: 449, mrp: 549, unit: "50 ml", discount: 18,
    rating: 4.6, reviewCount: 112, stockStatus: "In Stock",
    images: ["images/moisturizer-1.jpg"],
    attributes: { "Skin Type": "All", "Key Ingredient": "Hyaluronic Acid", "Volume": "50 ml", "Concern": "Hydration" },
    tags: ["Moisturizer", "Skincare", "Hydration"],
    featured: false, newArrival: false
  },
  {
    id: "P003",
    name: "Sunscreen SPF 50 PA+++",
    brand: "Lavenza",
    category: "Skincare",
    subCategory: "Sunscreen",
    description: "Broad spectrum SPF 50 PA+++ sunscreen, lightweight and non-greasy.",
    price: 349, mrp: 449, unit: "50 ml", discount: 22,
    rating: 4.6, reviewCount: 167, stockStatus: "In Stock",
    images: ["images/sunscreen-1.jpg"],
    attributes: { "SPF": "50", "Skin Type": "All", "Volume": "50 ml", "Concern": "Sun Protection" },
    tags: ["Sunscreen", "SPF", "Skincare"],
    featured: false, newArrival: true
  },
  {
    id: "P004",
    name: "Aloe Vera Soothing Gel",
    brand: "Lavenza",
    category: "Skincare",
    subCategory: "Gel",
    description: "Pure aloe vera gel for soothing and hydrating skin after sun exposure.",
    price: 199, mrp: 249, unit: "200 ml", discount: 20,
    rating: 4.6, reviewCount: 198, stockStatus: "In Stock",
    images: ["images/aloe-gel-1.jpg"],
    attributes: { "Skin Type": "All", "Key Ingredient": "Aloe Vera", "Volume": "200 ml", "Concern": "Hydration" },
    tags: ["Aloe Vera", "Gel", "Skincare"],
    featured: false, newArrival: false
  },
  {
    id: "P005",
    name: "Neem Purifying Face Wash",
    brand: "Lavenza",
    category: "Skincare",
    subCategory: "Face Wash",
    description: "Neem and turmeric face wash for clear, oil-free skin.",
    price: 199, mrp: 249, unit: "150 ml", discount: 20,
    rating: 4.4, reviewCount: 176, stockStatus: "In Stock",
    images: ["images/face-wash-1.jpg"],
    attributes: { "Skin Type": "Oily", "Key Ingredient": "Neem", "Volume": "150 ml", "Concern": "Acne" },
    tags: ["Face Wash", "Neem", "Skincare"],
    featured: false, newArrival: false
  },
  {
    id: "P006",
    name: "Rose Water Face Toner",
    brand: "Lavenza",
    category: "Skincare",
    subCategory: "Toner",
    description: "Alcohol-free rose water toner for refreshing and toning skin.",
    price: 249, mrp: 299, unit: "200 ml", discount: 17,
    rating: 4.5, reviewCount: 91, stockStatus: "In Stock",
    images: ["images/toner-1.jpg"],
    attributes: { "Skin Type": "All", "Key Ingredient": "Rose Water", "Volume": "200 ml", "Concern": "Pores" },
    tags: ["Toner", "Rose Water", "Skincare"],
    featured: false, newArrival: true
  },
  {
    id: "P007",
    name: "Overnight Repair Night Cream",
    brand: "Lavenza",
    category: "Skincare",
    subCategory: "Night Cream",
    description: "Overnight repair night cream with retinol and vitamin E.",
    price: 599, mrp: 749, unit: "50 ml", discount: 20,
    rating: 4.6, reviewCount: 57, stockStatus: "In Stock",
    images: ["images/night-cream-1.jpg"],
    attributes: { "Skin Type": "All", "Key Ingredient": "Retinol", "Volume": "50 ml", "Concern": "Anti-Aging" },
    tags: ["Night Cream", "Skincare", "Retinol"],
    featured: false, newArrival: true
  },
  {
    id: "P008",
    name: "Charcoal Detox Face Mask",
    brand: "Lavenza",
    category: "Skincare",
    subCategory: "Face Mask",
    description: "Activated charcoal peel-off mask for deep cleansing and pore tightening.",
    price: 279, mrp: 349, unit: "100 g", discount: 20,
    rating: 4.3, reviewCount: 84, stockStatus: "In Stock",
    images: ["images/face-mask-1.jpg"],
    attributes: { "Skin Type": "Oily", "Key Ingredient": "Charcoal", "Volume": "100 g", "Concern": "Pores" },
    tags: ["Face Mask", "Charcoal", "Skincare"],
    featured: false, newArrival: false
  },

  /* ============ COSMETICS ============ */
  {
    id: "P009",
    name: "Matte Velvet Lipstick",
    brand: "Lavenza",
    category: "Cosmetics",
    subCategory: "Lipstick",
    description: "Ultra-matte finish with rich colour payoff that lasts all day.",
    price: 299, mrp: 399, unit: "3.5 g", discount: 25,
    rating: 4.5, reviewCount: 89, stockStatus: "In Stock",
    images: ["images/lipstick-1.jpg", "images/lipstick-2.jpg"],
    attributes: { "Shade": "Rose Nude", "Finish": "Matte", "Skin Type": "All", "Net Weight": "3.5 g" },
    tags: ["Lipstick", "Matte", "Makeup"],
    featured: true, newArrival: false
  },
  {
    id: "P010",
    name: "Full Coverage Liquid Foundation",
    brand: "Lavenza",
    category: "Cosmetics",
    subCategory: "Foundation",
    description: "Full coverage liquid foundation with a natural, long-lasting finish.",
    price: 549, mrp: 699, unit: "30 ml", discount: 21,
    rating: 4.4, reviewCount: 103, stockStatus: "In Stock",
    images: ["images/foundation-1.jpg"],
    attributes: { "Shade": "Natural Beige", "Finish": "Natural", "Skin Type": "All", "Volume": "30 ml" },
    tags: ["Foundation", "Makeup"],
    featured: false, newArrival: false
  },
  {
    id: "P011",
    name: "Compact Powder SPF 15",
    brand: "Lavenza",
    category: "Cosmetics",
    subCategory: "Compact Powder",
    description: "Oil-control compact powder with SPF 15 for a shine-free look.",
    price: 349, mrp: 449, unit: "9 g", discount: 22,
    rating: 4.3, reviewCount: 67, stockStatus: "In Stock",
    images: ["images/compact-1.jpg"],
    attributes: { "Shade": "Ivory", "Finish": "Matte", "Skin Type": "Oily", "Net Weight": "9 g" },
    tags: ["Compact", "Powder", "Makeup"],
    featured: false, newArrival: false
  },
  {
    id: "P012",
    name: "Intense Black Kajal",
    brand: "Lavenza",
    category: "Cosmetics",
    subCategory: "Kajal",
    description: "Smudge-proof kajal for intense black, dramatic eyes.",
    price: 199, mrp: 249, unit: "0.35 g", discount: 20,
    rating: 4.5, reviewCount: 211, stockStatus: "In Stock",
    images: ["images/kajal-1.jpg"],
    attributes: { "Shade": "Black", "Finish": "Matte", "Skin Type": "All", "Net Weight": "0.35 g" },
    tags: ["Kajal", "Makeup", "Eyes"],
    featured: false, newArrival: false
  },
  {
    id: "P013",
    name: "Volume Boost Mascara",
    brand: "Lavenza",
    category: "Cosmetics",
    subCategory: "Mascara",
    description: "Volumizing mascara for dramatically fuller lashes.",
    price: 349, mrp: 449, unit: "10 ml", discount: 22,
    rating: 4.4, reviewCount: 87, stockStatus: "In Stock",
    images: ["images/mascara-1.jpg"],
    attributes: { "Shade": "Black", "Finish": "Volumizing", "Skin Type": "All", "Volume": "10 ml" },
    tags: ["Mascara", "Makeup", "Eyes"],
    featured: false, newArrival: false
  },
  {
    id: "P014",
    name: "Peach Glow Blush",
    brand: "Lavenza",
    category: "Cosmetics",
    subCategory: "Blush",
    description: "Silky powder blush for a natural, healthy peach glow.",
    price: 279, mrp: 349, unit: "5 g", discount: 20,
    rating: 4.4, reviewCount: 62, stockStatus: "In Stock",
    images: ["images/blush-1.jpg"],
    attributes: { "Shade": "Peach", "Finish": "Natural", "Skin Type": "All", "Net Weight": "5 g" },
    tags: ["Blush", "Makeup", "Face"],
    featured: false, newArrival: false
  },
  {
    id: "P015",
    name: "Precision Black Eyeliner",
    brand: "Lavenza",
    category: "Cosmetics",
    subCategory: "Eyeliner",
    description: "Precision tip eyeliner for sharp, defined lines that last all day.",
    price: 229, mrp: 279, unit: "5 ml", discount: 18,
    rating: 4.4, reviewCount: 81, stockStatus: "In Stock",
    images: ["images/eyeliner-1.jpg"],
    attributes: { "Shade": "Black", "Finish": "Matte", "Skin Type": "All", "Volume": "5 ml" },
    tags: ["Eyeliner", "Makeup", "Eyes"],
    featured: false, newArrival: false
  },
  {
    id: "P016",
    name: "Complete Makeup Kit",
    brand: "Lavenza",
    category: "Cosmetics",
    subCategory: "Makeup Kit",
    description: "All-in-one makeup kit with lipstick, kajal, mascara and compact.",
    price: 1299, mrp: 1699, unit: "1 Set", discount: 24,
    rating: 4.7, reviewCount: 45, stockStatus: "In Stock",
    images: ["images/makeup-kit-1.jpg"],
    attributes: { "Type": "Kit", "Items": "4", "Skin Type": "All", "Packaging": "Box" },
    tags: ["Makeup Kit", "Gift", "Cosmetics"],
    featured: true, newArrival: true
  },

  /* ============ HAIRCARE ============ */
  {
    id: "P017",
    name: "Anti-Dandruff Shampoo",
    brand: "Lavenza",
    category: "Haircare",
    subCategory: "Shampoo",
    description: "Gentle anti-dandruff shampoo with tea tree oil and neem.",
    price: 279, mrp: 349, unit: "200 ml", discount: 20,
    rating: 4.3, reviewCount: 92, stockStatus: "In Stock",
    images: ["images/shampoo-1.jpg"],
    attributes: { "Volume": "200 ml", "Hair Type": "Dandruff Prone", "Key Ingredient": "Tea Tree", "Fragrance": "Neem" },
    tags: ["Shampoo", "Haircare", "Anti-Dandruff"],
    featured: false, newArrival: false
  },
  {
    id: "P018",
    name: "Argan Oil Hair Serum",
    brand: "Lavenza",
    category: "Haircare",
    subCategory: "Hair Serum",
    description: "Frizz-control hair serum enriched with argan oil for silky hair.",
    price: 329, mrp: 399, unit: "50 ml", discount: 18,
    rating: 4.5, reviewCount: 64, stockStatus: "In Stock",
    images: ["images/hair-serum-1.jpg"],
    attributes: { "Volume": "50 ml", "Hair Type": "All", "Key Ingredient": "Argan Oil", "Concern": "Frizz" },
    tags: ["Hair Serum", "Argan Oil", "Haircare"],
    featured: false, newArrival: true
  },
  {
    id: "P019",
    name: "Silk Smooth Conditioner",
    brand: "Lavenza",
    category: "Haircare",
    subCategory: "Conditioner",
    description: "Silky smooth conditioner for frizz-free, manageable hair.",
    price: 289, mrp: 349, unit: "200 ml", discount: 17,
    rating: 4.3, reviewCount: 73, stockStatus: "In Stock",
    images: ["images/conditioner-1.jpg"],
    attributes: { "Volume": "200 ml", "Hair Type": "All", "Key Ingredient": "Silk Protein", "Concern": "Frizz" },
    tags: ["Conditioner", "Haircare", "Silk"],
    featured: false, newArrival: false
  },
  {
    id: "P020",
    name: "Coconut & Almond Hair Oil",
    brand: "Lavenza",
    category: "Haircare",
    subCategory: "Hair Oil",
    description: "Nourishing hair oil with coconut and almond for stronger hair.",
    price: 299, mrp: 379, unit: "200 ml", discount: 21,
    rating: 4.5, reviewCount: 134, stockStatus: "In Stock",
    images: ["images/hair-oil-1.jpg"],
    attributes: { "Volume": "200 ml", "Hair Type": "All", "Key Ingredient": "Coconut, Almond", "Concern": "Hair Fall" },
    tags: ["Hair Oil", "Coconut", "Haircare"],
    featured: false, newArrival: false
  },
  {
    id: "P021",
    name: "Keratin Repair Hair Mask",
    brand: "Lavenza",
    category: "Haircare",
    subCategory: "Hair Mask",
    description: "Deep conditioning keratin hair mask for damaged hair.",
    price: 499, mrp: 599, unit: "200 g", discount: 17,
    rating: 4.5, reviewCount: 46, stockStatus: "In Stock",
    images: ["images/hair-mask-1.jpg"],
    attributes: { "Volume": "200 g", "Hair Type": "Damaged", "Key Ingredient": "Keratin", "Concern": "Repair" },
    tags: ["Hair Mask", "Keratin", "Haircare"],
    featured: false, newArrival: false
  },
  {
    id: "P022",
    name: "Hair Spa Cream",
    brand: "Lavenza",
    category: "Haircare",
    subCategory: "Hair Spa",
    description: "Salon-style hair spa cream for smooth, shiny, manageable hair.",
    price: 449, mrp: 549, unit: "250 g", discount: 18,
    rating: 4.4, reviewCount: 52, stockStatus: "In Stock",
    images: ["images/hair-spa-1.jpg"],
    attributes: { "Volume": "250 g", "Hair Type": "All", "Key Ingredient": "Shea Butter", "Concern": "Damage" },
    tags: ["Hair Spa", "Haircare"],
    featured: false, newArrival: true
  },

  /* ============ FRAGRANCE ============ */
  {
    id: "P023",
    name: "Jasmine Eau De Parfum",
    brand: "Lavenza",
    category: "Fragrance",
    subCategory: "Perfume",
    description: "Long-lasting jasmine eau de parfum for a signature floral scent.",
    price: 899, mrp: 1199, unit: "50 ml", discount: 25,
    rating: 4.7, reviewCount: 52, stockStatus: "In Stock",
    images: ["images/perfume-1.jpg"],
    attributes: { "Volume": "50 ml", "Fragrance": "Jasmine", "Type": "Eau De Parfum", "Usage": "Evening" },
    tags: ["Perfume", "Jasmine", "Fragrance"],
    featured: true, newArrival: false
  },
  {
    id: "P024",
    name: "Rose Body Mist",
    brand: "Lavenza",
    category: "Fragrance",
    subCategory: "Body Mist",
    description: "Refreshing rose-scented body mist for all-day freshness.",
    price: 349, mrp: 449, unit: "120 ml", discount: 22,
    rating: 4.4, reviewCount: 78, stockStatus: "In Stock",
    images: ["images/rose-mist-1.jpg"],
    attributes: { "Volume": "120 ml", "Fragrance": "Rose", "Type": "Body Mist", "Usage": "Daily" },
    tags: ["Rose", "Body Mist", "Fragrance"],
    featured: true, newArrival: true
  },
  {
    id: "P025",
    name: "Citrus Fresh Deodorant",
    brand: "Lavenza",
    category: "Fragrance",
    subCategory: "Deodorant",
    description: "Long-lasting citrus deodorant for all-day freshness.",
    price: 249, mrp: 299, unit: "150 ml", discount: 17,
    rating: 4.2, reviewCount: 49, stockStatus: "In Stock",
    images: ["images/deodorant-1.jpg"],
    attributes: { "Volume": "150 ml", "Fragrance": "Citrus", "Type": "Deodorant", "Usage": "Daily" },
    tags: ["Deodorant", "Citrus", "Fragrance"],
    featured: false, newArrival: false
  },
  {
    id: "P026",
    name: "Oudh Attar",
    brand: "Lavenza",
    category: "Fragrance",
    subCategory: "Attar",
    description: "Traditional oudh attar, alcohol-free and long-lasting.",
    price: 799, mrp: 999, unit: "12 ml", discount: 20,
    rating: 4.8, reviewCount: 29, stockStatus: "In Stock",
    images: ["images/attar-1.jpg"],
    attributes: { "Volume": "12 ml", "Fragrance": "Oudh", "Type": "Attar", "Usage": "Special Occasions" },
    tags: ["Attar", "Oudh", "Fragrance"],
    featured: false, newArrival: true
  },

  /* ============ SWEETS (FESTIVE) ============ */
  {
    id: "P027",
    name: "Premium Kaju Katli",
    brand: "Lavenza",
    category: "Sweets",
    subCategory: "Kaju",
    description: "Premium cashew fudge made with pure ghee and finest cashews.",
    price: 450, mrp: 550, unit: "500 g", discount: 18,
    rating: 4.8, reviewCount: 212, stockStatus: "In Stock",
    images: ["images/kaju-katli-1.jpg", "images/kaju-katli-2.jpg"],
    attributes: { "Weight": "500 g", "Ingredients": "Cashew, Sugar, Ghee", "Shelf Life": "15 days", "Type": "Kaju", "Vegetarian": "Yes" },
    tags: ["Kaju Katli", "Sweets", "Diwali"],
    featured: true, newArrival: false
  },
  {
    id: "P028",
    name: "Motichoor Laddu",
    brand: "Lavenza",
    category: "Sweets",
    subCategory: "Laddu",
    description: "Traditional motichoor laddus made with pure desi ghee.",
    price: 380, mrp: 420, unit: "500 g", discount: 10,
    rating: 4.7, reviewCount: 134, stockStatus: "In Stock",
    images: ["images/laddu-1.jpg"],
    attributes: { "Weight": "500 g", "Ingredients": "Gram Flour, Sugar, Ghee", "Shelf Life": "12 days", "Type": "Laddu", "Vegetarian": "Yes" },
    tags: ["Laddu", "Sweets", "Indian"],
    featured: false, newArrival: false
  },
  {
    id: "P029",
    name: "Soft Gulab Jamun",
    brand: "Lavenza",
    category: "Sweets",
    subCategory: "Bengali Sweets",
    description: "Soft and juicy gulab jamuns in delicate sugar syrup.",
    price: 320, mrp: 380, unit: "1 kg", discount: 16,
    rating: 4.6, reviewCount: 145, stockStatus: "In Stock",
    images: ["images/gulab-jamun-1.jpg"],
    attributes: { "Weight": "1 kg", "Ingredients": "Milk, Sugar, Flour", "Shelf Life": "7 days", "Type": "Bengali Sweets", "Vegetarian": "Yes" },
    tags: ["Gulab Jamun", "Sweets", "Bengali"],
    featured: false, newArrival: false
  },
  {
    id: "P030",
    name: "Spongy Rasgulla",
    brand: "Lavenza",
    category: "Sweets",
    subCategory: "Bengali Sweets",
    description: "Spongy and juicy rasgullas in light sugar syrup.",
    price: 380, mrp: 440, unit: "1 kg", discount: 14,
    rating: 4.6, reviewCount: 112, stockStatus: "In Stock",
    images: ["images/rasgulla-1.jpg"],
    attributes: { "Weight": "1 kg", "Ingredients": "Milk, Sugar, Lemon", "Shelf Life": "7 days", "Type": "Bengali Sweets", "Vegetarian": "Yes" },
    tags: ["Rasgulla", "Sweets", "Bengali"],
    featured: false, newArrival: false
  },
  {
    id: "P031",
    name: "Flaky Soan Papdi",
    brand: "Lavenza",
    category: "Sweets",
    subCategory: "Soan Papdi",
    description: "Flaky and melt-in-mouth soan papdi, a classic Indian sweet.",
    price: 280, mrp: 320, unit: "500 g", discount: 13,
    rating: 4.3, reviewCount: 67, stockStatus: "In Stock",
    images: ["images/soan-papdi-1.jpg"],
    attributes: { "Weight": "500 g", "Ingredients": "Flour, Sugar, Ghee", "Shelf Life": "20 days", "Type": "Soan Papdi", "Vegetarian": "Yes" },
    tags: ["Soan Papdi", "Sweets", "Indian"],
    featured: false, newArrival: false
  },
  {
    id: "P032",
    name: "Besan Laddu",
    brand: "Lavenza",
    category: "Sweets",
    subCategory: "Laddu",
    description: "Traditional besan laddus with a rich, nutty flavour.",
    price: 350, mrp: 400, unit: "500 g", discount: 13,
    rating: 4.5, reviewCount: 98, stockStatus: "In Stock",
    images: ["images/besan-laddu-1.jpg"],
    attributes: { "Weight": "500 g", "Ingredients": "Gram Flour, Sugar, Ghee", "Shelf Life": "15 days", "Type": "Laddu", "Vegetarian": "Yes" },
    tags: ["Besan Laddu", "Sweets", "Indian"],
    featured: false, newArrival: false
  },

  /* ============ CHOCOLATES (FESTIVE) ============ */
  {
    id: "P033",
    name: "Dark Chocolate 70%",
    brand: "Lavenza",
    category: "Chocolates",
    subCategory: "Dark Chocolate",
    description: "Rich dark chocolate with 70% cocoa for a guilt-free indulgence.",
    price: 249, mrp: 299, unit: "100 g", discount: 17,
    rating: 4.6, reviewCount: 156, stockStatus: "In Stock",
    images: ["images/dark-choco-1.jpg"],
    attributes: { "Weight": "100 g", "Cocoa Percentage": "70%", "Flavour": "Dark", "Country": "Belgium", "Vegetarian": "Yes" },
    tags: ["Dark Chocolate", "Chocolate", "Snack"],
    featured: true, newArrival: false
  },
  {
    id: "P034",
    name: "Creamy Milk Chocolate",
    brand: "Lavenza",
    category: "Chocolates",
    subCategory: "Milk Chocolate",
    description: "Smooth and creamy milk chocolate made with premium cocoa.",
    price: 199, mrp: 249, unit: "100 g", discount: 20,
    rating: 4.5, reviewCount: 189, stockStatus: "In Stock",
    images: ["images/milk-choco-1.jpg"],
    attributes: { "Weight": "100 g", "Cocoa Percentage": "Milk", "Flavour": "Milk", "Country": "India", "Vegetarian": "Yes" },
    tags: ["Milk Chocolate", "Chocolate", "Snack"],
    featured: false, newArrival: false
  },
  {
    id: "P035",
    name: "Assorted Chocolate Box",
    brand: "Lavenza",
    category: "Chocolates",
    subCategory: "Assorted",
    description: "Box of 12 assorted chocolates – milk, dark and white.",
    price: 499, mrp: 599, unit: "Box of 12", discount: 17,
    rating: 4.5, reviewCount: 76, stockStatus: "In Stock",
    images: ["images/assorted-choco-1.jpg"],
    attributes: { "Weight": "180 g", "Cocoa Percentage": "Assorted", "Flavour": "Assorted", "Country": "India", "Vegetarian": "Yes" },
    tags: ["Chocolate", "Assorted", "Gift"],
    featured: false, newArrival: true
  },
  {
    id: "P036",
    name: "Chocolate Gift Box",
    brand: "Lavenza",
    category: "Chocolates",
    subCategory: "Gift Box",
    description: "Elegant gift box with 16 assorted premium chocolates.",
    price: 699, mrp: 899, unit: "Box of 16", discount: 22,
    rating: 4.7, reviewCount: 41, stockStatus: "In Stock",
    images: ["images/choco-gift-1.jpg"],
    attributes: { "Weight": "240 g", "Cocoa Percentage": "Assorted", "Flavour": "Assorted", "Country": "India", "Vegetarian": "Yes" },
    tags: ["Gift", "Chocolate", "Box"],
    featured: false, newArrival: true
  },

  /* ============ SNACKS ============ */
  {
    id: "P037",
    name: "Chocolate Chip Cookies",
    brand: "Lavenza",
    category: "Snacks",
    subCategory: "Cookies",
    description: "Crunchy chocolate chip cookies, perfect with tea or coffee.",
    price: 149, mrp: 199, unit: "300 g", discount: 25,
    rating: 4.3, reviewCount: 118, stockStatus: "In Stock",
    images: ["images/cookies-1.jpg"],
    attributes: { "Weight": "300 g", "Flavour": "Chocolate", "Type": "Cookies", "Vegetarian": "Yes" },
    tags: ["Cookies", "Snack", "Chocolate"],
    featured: false, newArrival: false
  },
  {
    id: "P038",
    name: "Spicy Namkeen Mix",
    brand: "Lavenza",
    category: "Snacks",
    subCategory: "Namkeen",
    description: "Spicy and crunchy namkeen mix for tea-time snacking.",
    price: 129, mrp: 159, unit: "400 g", discount: 19,
    rating: 4.2, reviewCount: 94, stockStatus: "In Stock",
    images: ["images/namkeen-1.jpg"],
    attributes: { "Weight": "400 g", "Flavour": "Spicy", "Type": "Namkeen", "Vegetarian": "Yes" },
    tags: ["Namkeen", "Snack", "Indian"],
    featured: false, newArrival: false
  },
  {
    id: "P039",
    name: "Premium Dry Fruit Mix",
    brand: "Lavenza",
    category: "Snacks",
    subCategory: "Dry Fruits",
    description: "Premium mix of almonds, cashews, pistachios and raisins.",
    price: 599, mrp: 699, unit: "500 g", discount: 14,
    rating: 4.7, reviewCount: 102, stockStatus: "In Stock",
    images: ["images/dry-fruit-1.jpg"],
    attributes: { "Weight": "500 g", "Flavour": "Natural", "Type": "Dry Fruits", "Vegetarian": "Yes" },
    tags: ["Dry Fruits", "Snack", "Healthy"],
    featured: false, newArrival: false
  },
  {
    id: "P040",
    name: "Classic Salted Chips",
    brand: "Lavenza",
    category: "Snacks",
    subCategory: "Chips",
    description: "Crispy salted potato chips, perfect for movie nights.",
    price: 99, mrp: 129, unit: "150 g", discount: 23,
    rating: 4.2, reviewCount: 156, stockStatus: "In Stock",
    images: ["images/chips-1.jpg"],
    attributes: { "Weight": "150 g", "Flavour": "Salted", "Type": "Chips", "Vegetarian": "Yes" },
    tags: ["Chips", "Snack"],
    featured: false, newArrival: false
  },

  /* ============ GIFTS (FESTIVE) ============ */
  {
    id: "P041",
    name: "Premium Gift Hamper",
    brand: "Lavenza",
    category: "Gifts",
    subCategory: "Gift Hamper",
    description: "Curated gift hamper with chocolates, sweets and a scented candle.",
    price: 999, mrp: 1299, unit: "Set", discount: 23,
    rating: 4.9, reviewCount: 45, stockStatus: "In Stock",
    images: ["images/hamper-1.jpg"],
    attributes: { "Type": "Gift Hamper", "Occasion": "Festival", "Items": "Chocolates, Sweets, Candle", "Packaging": "Premium Box" },
    tags: ["Gift", "Hamper", "Festival", "Diwali"],
    featured: true, newArrival: true
  },
  {
    id: "P042",
    name: "Diwali Festival Gift Pack",
    brand: "Lavenza",
    category: "Gifts",
    subCategory: "Festival Gift",
    description: "Complete festival gift pack with sweets, chocolates and dry fruits.",
    price: 1499, mrp: 1899, unit: "Set", discount: 21,
    rating: 4.9, reviewCount: 23, stockStatus: "In Stock",
    images: ["images/festival-gift-1.jpg"],
    attributes: { "Type": "Festival Gift", "Occasion": "Diwali", "Items": "Sweets, Chocolates, Dry Fruits", "Packaging": "Premium Box" },
    tags: ["Gift", "Festival", "Diwali"],
    featured: true, newArrival: true
  },
  {
    id: "P043",
    name: "Beauty Gift Set",
    brand: "Lavenza",
    category: "Gifts",
    subCategory: "Beauty Gift",
    description: "Elegant beauty gift set with serum, lipstick and body mist.",
    price: 899, mrp: 1199, unit: "1 Set", discount: 25,
    rating: 4.6, reviewCount: 34, stockStatus: "In Stock",
    images: ["images/beauty-gift-1.jpg"],
    attributes: { "Type": "Beauty Gift", "Occasion": "Birthday", "Items": "3", "Packaging": "Gift Box" },
    tags: ["Gift", "Beauty", "Set"],
    featured: false, newArrival: true
  },

  /* ============ HOUSEHOLD ============ */
  {
    id: "P044",
    name: "Vanilla Scented Candle",
    brand: "Lavenza",
    category: "Household",
    subCategory: "Candle",
    description: "Hand-poured scented candle with warm vanilla notes.",
    price: 449, mrp: 549, unit: "1 Piece", discount: 18,
    rating: 4.8, reviewCount: 37, stockStatus: "In Stock",
    images: ["images/candle-1.jpg"],
    attributes: { "Volume": "200 g", "Fragrance": "Vanilla", "Material": "Soy Wax", "Usage": "Home Decor" },
    tags: ["Candle", "Vanilla", "Household"],
    featured: false, newArrival: true
  },
  {
    id: "P045",
    name: "Lavender Room Freshener",
    brand: "Lavenza",
    category: "Household",
    subCategory: "Room Freshener",
    description: "Long-lasting lavender room freshener for a calm ambience.",
    price: 249, mrp: 299, unit: "250 ml", discount: 17,
    rating: 4.3, reviewCount: 58, stockStatus: "In Stock",
    images: ["images/room-freshener-1.jpg"],
    attributes: { "Volume": "250 ml", "Fragrance": "Lavender", "Material": "Liquid", "Usage": "Home" },
    tags: ["Room Freshener", "Lavender", "Household"],
    featured: false, newArrival: false
  },
  {
    id: "P046",
    name: "Rose Hand Wash",
    brand: "Lavenza",
    category: "Household",
    subCategory: "Hand Wash",
    description: "Gentle rose hand wash with a moisturizing formula.",
    price: 149, mrp: 199, unit: "250 ml", discount: 25,
    rating: 4.5, reviewCount: 88, stockStatus: "In Stock",
    images: ["images/hand-wash-1.jpg"],
    attributes: { "Volume": "250 ml", "Fragrance": "Rose", "Material": "Liquid", "Usage": "Hand Hygiene" },
    tags: ["Hand Wash", "Rose", "Household"],
    featured: false, newArrival: false
  },
  {
    id: "P047",
    name: "Sandalwood Fragrance Diffuser",
    brand: "Lavenza",
    category: "Household",
    subCategory: "Diffuser",
    description: "Elegant sandalwood fragrance diffuser for continuous aroma.",
    price: 599, mrp: 749, unit: "200 ml", discount: 20,
    rating: 4.6, reviewCount: 33, stockStatus: "In Stock",
    images: ["images/diffuser-1.jpg"],
    attributes: { "Volume": "200 ml", "Fragrance": "Sandalwood", "Material": "Glass", "Usage": "Home" },
    tags: ["Diffuser", "Sandalwood", "Household"],
    featured: false, newArrival: true
  },
  {
    id: "P048",
    name: "Jasmine Scented Candle",
    brand: "Lavenza",
    category: "Household",
    subCategory: "Candle",
    description: "Soothing jasmine scented candle for a relaxing ambience.",
    price: 399, mrp: 499, unit: "1 Piece", discount: 20,
    rating: 4.7, reviewCount: 41, stockStatus: "In Stock",
    images: ["images/jasmine-candle-1.jpg"],
    attributes: { "Volume": "180 g", "Fragrance": "Jasmine", "Material": "Soy Wax", "Usage": "Home Decor" },
    tags: ["Candle", "Jasmine", "Household"],
    featured: false, newArrival: false
  }
];

// Expose to global scope (script.js reads from window.dummyProducts)
window.dummyProducts = dummyProducts;